managementActivation: true
managementAddress: localhost
managementPort: 3232
managementResourceBase: ./porta-www/build
credentialPath: ./credentials.yml
proxyThreadPoolCoreSize: 10
proxyThreadPoolMaxSize: 50
proxyThreadPoolIdleSecond: 600
proxyThreadPoolQueueSize: 30
sessionMapping:
  mysql:
    allowedHosts: [127.0.0.1]
    forbiddenHosts: []
    bufferSize: 0
    connectionTimeout: 5
    keepAlive: false
    proxyBindAddress: localhost
    proxyPort: 9336
    remoteHosts: [192.168.1.157:9336, 192.168.1.157:9336, 192.168.1.157:9336]
    sessionMode: LOAD_BALANCE_ROUND_ROBIN
    standAloneRetry: 3
    loadBalanceRatio: 
    failedCircularRetry: 3
    soTimeout: 0
    tcpNoDelay: false
  kafka:
    allowedHosts: [127.0.0.1]
    forbiddenHosts: []
    bufferSize: 0
    connectionTimeout: 0
    keepAlive: false
    proxyBindAddress: localhost
    proxyPort: 8092
    remoteHosts: [192.168.1.152:8092]
    sessionMode: STAND_ALONE
    standAloneRetry: 3
    loadBalanceRatio: 
    failedCircularRetry: 3
    soTimeout: 0
    tcpNoDelay: false
  oracle:
    allowedHosts: [127.0.0.1]
    forbiddenHosts: []
    bufferSize: 0
    connectionTimeout: 3
    keepAlive: true
    proxyBindAddress: localhost
    proxyPort: 1521
    remoteHosts: [192.168.1.157:1521]
    sessionMode: STAND_ALONE
    standAloneRetry: 3
    loadBalanceRatio: 
    failedCircularRetry: 6
    soTimeout: 60000
    tcpNoDelay: true

