package org.chaostocosmos.porta;

/**
 * Enum of representing resource type
 */
public enum RESOURCE {
    APP,
    MANAGEMENT,
    CPU,
    MEMORY,
    THREAD,
    THREAD_POOL,  
    SESSION_INFO,
    SESSIONS_INFO,
    SESSION_SIMPLE,      
    SESSION_USAGE,    
    SESSIONS_USAGE,
    SESSION_THROUGHPUT,
    SESSIONS_THROUGHPUT,
    SESSION_MAPPINGS,
    SESSION_NAME,
    SESSION_MODE,
    SESSION_SEND_SIZE,
    SESSION_RECEIVE_SIZE,
    SESSION_SEND_SIZE_TOTAL,
    SESSION_RECEIVE_SIZE_TOTAL,
    SESSION_TOTAL_SUCCESS,
    SESSION_SEND_SUCCESS_COUNT,
    SESSION_RECEIVE_SUCCESS_COUNT,
    SESSION_TOTAL_FAIL,
    SESSION_SEND_FAIL_COUNT,
    SESSION_RECEIVE_FAIL_COUNT,
    APPLY_SESSION_INFO,
    APPLY_SESSIONS_INFO,
    SAVE_SESSION_INFO,
    SAVE_SESSIONS_INFO,
    APPLY_SAVE_SESSION_INFO,    
    APPLY_SAVE_SESSIONS_INFO,
}
