appConfigs: !!org.chaostocosmos.porta.properties.AppConfigs
  name: Porta
  statisticsProbeMillis: 1000
  version: 1.0.0
managementConfigs: !!org.chaostocosmos.porta.properties.ManagementConfigs
  managementActivation: true
  managementAddress: localhost
  managementPort: 3232
  managementResourceBase: ./porta-web
threadPoolConfigs: !!org.chaostocosmos.porta.properties.ThreadPoolConfigs
  threadPoolCoreSize: 30
  threadPoolMaxSize: 50
  threadPoolIdleSecond: 10
  threadPoolLimitSize: 1000
  threadPoolQueueSize: 30
sessionMappingConfigs:
  mysql: !!org.chaostocosmos.porta.properties.SessionMappingConfigs
    allowedHosts:
    - 127.0.0.1
    bindAddress: localhost
    bufferSize: 0
    connectionTimeout: 5
    failedCircularRetry: 3
    forbiddenHosts: [
      ]
    keepAlive: false
    loadBalanceRatio: null
    port: 9336
    remoteHosts:
    - 192.168.1.157:9336
    - 192.168.1.157:9336
    - 192.168.1.157:9336
    sessionMode: LOAD_BALANCE_ROUND_ROBIN
    soTimeout: 0
    retry: 3
    retryInterval: 500
    tcpNoDelay: false
  kafka: !!org.chaostocosmos.porta.properties.SessionMappingConfigs
    allowedHosts:
    - 127.0.0.1
    bindAddress: localhost
    bufferSize: 0
    connectionTimeout: 0
    failedCircularRetry: 3
    forbiddenHosts: [
      ]
    keepAlive: false
    loadBalanceRatio: null
    port: 8092
    remoteHosts:
    - 192.168.1.152:8092
    sessionMode: STAND_ALONE
    soTimeout: 0
    retry: 3
    retryInterval: 500
    tcpNoDelay: false
  oracle: !!org.chaostocosmos.porta.properties.SessionMappingConfigs
    allowedHosts:
    - 127.0.0.1
    bindAddress: localhost
    bufferSize: 0
    connectionTimeout: 5
    failedCircularRetry: 6
    forbiddenHosts: [
      ]
    keepAlive: true
    loadBalanceRatio: null
    port: 1521
    remoteHosts:
    - 192.168.1.157:1521
    sessionMode: STAND_ALONE
    soTimeout: 6000
    retry: 3
    retryInterval: 500
    tcpNoDelay: true
