## Porta credential configuration

  superUser: super
  superPassword: 1234
  sessions:
    - session: mysql
      credential:
      - username: admin
        password: 1234
        grant: 
          - ADMIN
          - OPERATOR
      - username: system
        password: 1234
        grant:
          - MONITOR
    - session: kafka
      credential:
      - username: Simple
        password: 111
        grant: 
          - ADMIN
          - OPERATOR
    - session: oracle
      credential: 
      - username: test
        password: 1234
        grant:
          - ADMIN

