## Porta messages configuration

system:
  SYSCODE001: 
  SYSCODE002: 

information:
  INFOCODE001: 
  INFOCODE002: 

debug: 
  DEBUG001: 

error:
  ERRCODE001: 'Requested type - $ was having wrong value. Resource request type just be allowed of memory or cpu.'
  ERRCODE002: 'There could not find handler configuration in handler.yml $'
  ERRCODE003: 'There could not find servlet configuration in handler.yml $'
  ERRCODE004: 'Response Map is null or zero size. Please define response Map on $'
  ERRCODE005: 'Response contentType is not defined at return Map on $'
  ERRCODE006: 'Response resCode is not defined at return Map on $'
  ERRCODE007: 'Not supported HTTP response data type: $'
  ERRCODE008: 'Not exist resource type: $'
